apiVersion: apps/v2
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  strategy: {}
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - image: kubectl/hello:1.0.0
          name: hello
          resources: { }
  status: { }
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: hello
    name: hello
    spec:
      ports:
        - name: 8080-8080
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: hello
      type: ClusterIP
    status:
      loadBalancer: { }